import type { ReportTemplate, Shift, ShiftType, Workplace } from './schema';

/**
 * 網頁預覽用的假資料,只在 localStorage 完全沒有資料(第一次載入)時套用一次,
 * 之後使用者自己的異動都會照常存進 localStorage,不會被這份資料蓋掉。
 *
 * 涵蓋範圍(方便手動測試統計頁所有情境):
 * - 三種計薪方式(月薪/時薪/日薪)+ 三種發薪頻率(月結/週結/日結)+ 一份還沒設定發薪日的工作
 * - 深夜加給(部分重疊/全部重疊)、假日加給、手動覆寫金額、休息日標記
 * - 每份工作都有「今天(2026-08-19)之前」跟「之後」的班次,方便測截至今日/未來拆分
 */

export const seedWorkplaces: Workplace[] = [
  {
    id: 1,
    name: '正職辦公室',
    wageType: 'monthly',
    monthlySalary: 42000,
    onboardDate: '2024-01-01',
    isCurrentlyEmployed: true,
    endDate: null,
    defaultHourlyRate: null,
    defaultDailyRate: null,
    payCycle: 'monthly',
    paydayDayOfMonth: 5,
    paydayWeekday: null,
    periodStartDayOfMonth: 1,
    periodStartWeekday: null,
    periodEndDayOfMonth: null,
    periodEndIsEndOfMonth: true,
    periodEndWeekday: null,
  },
  {
    id: 2,
    name: '超商時薪工讀',
    wageType: 'hourly',
    monthlySalary: null,
    onboardDate: null,
    isCurrentlyEmployed: null,
    endDate: null,
    defaultHourlyRate: 183,
    defaultDailyRate: null,
    payCycle: 'weekly',
    paydayDayOfMonth: null,
    paydayWeekday: 5,
    periodStartDayOfMonth: null,
    periodStartWeekday: 1,
    periodEndDayOfMonth: null,
    periodEndIsEndOfMonth: null,
    periodEndWeekday: 5,
  },
  {
    id: 3,
    name: '工地日薪師傅',
    wageType: 'daily',
    monthlySalary: null,
    onboardDate: null,
    isCurrentlyEmployed: null,
    endDate: null,
    defaultHourlyRate: null,
    defaultDailyRate: 1600,
    payCycle: 'daily',
    paydayDayOfMonth: null,
    paydayWeekday: null,
    periodStartDayOfMonth: null,
    periodStartWeekday: null,
    periodEndDayOfMonth: null,
    periodEndIsEndOfMonth: null,
    periodEndWeekday: null,
  },
  {
    id: 4,
    name: '家教兼職',
    wageType: 'hourly',
    monthlySalary: null,
    onboardDate: null,
    isCurrentlyEmployed: null,
    endDate: null,
    defaultHourlyRate: 500,
    defaultDailyRate: null,
    payCycle: null,
    paydayDayOfMonth: null,
    paydayWeekday: null,
    periodStartDayOfMonth: null,
    periodStartWeekday: null,
    periodEndDayOfMonth: null,
    periodEndIsEndOfMonth: null,
    periodEndWeekday: null,
  },
];

export const seedShiftTypes: ShiftType[] = [
  {
    id: 1,
    workplaceId: 1,
    name: '上班',
    startTime: '09:00',
    endTime: '18:00',
    hourlyRate: null,
    dailyRate: null,
    breakMinutes: 60,
    breakPaid: false,
    nightRateEnabled: false,
    nightMultiplier: null,
    nightStart: null,
    nightEnd: null,
    holidayRateEnabled: false,
    holidayPercent: null,
  },
  {
    id: 2,
    workplaceId: 2,
    name: '早班',
    startTime: '09:00',
    endTime: '17:00',
    hourlyRate: null,
    dailyRate: null,
    breakMinutes: 60,
    breakPaid: false,
    nightRateEnabled: false,
    nightMultiplier: null,
    nightStart: null,
    nightEnd: null,
    holidayRateEnabled: true,
    holidayPercent: 33,
  },
  {
    id: 3,
    workplaceId: 2,
    name: '晚班',
    startTime: '17:00',
    endTime: '22:00',
    hourlyRate: null,
    dailyRate: null,
    breakMinutes: 30,
    breakPaid: false,
    nightRateEnabled: true,
    nightMultiplier: 1.34,
    nightStart: '21:00',
    nightEnd: '06:00',
    holidayRateEnabled: false,
    holidayPercent: null,
  },
  {
    id: 4,
    workplaceId: 2,
    name: '夜班',
    startTime: '22:00',
    endTime: '06:00',
    hourlyRate: 200,
    dailyRate: null,
    breakMinutes: 0,
    breakPaid: false,
    nightRateEnabled: true,
    nightMultiplier: 1.5,
    nightStart: '22:00',
    nightEnd: '06:00',
    holidayRateEnabled: false,
    holidayPercent: null,
  },
  {
    id: 5,
    workplaceId: 3,
    name: '工班',
    startTime: '07:00',
    endTime: '16:00',
    hourlyRate: null,
    dailyRate: null,
    breakMinutes: null,
    breakPaid: null,
    nightRateEnabled: false,
    nightMultiplier: null,
    nightStart: null,
    nightEnd: null,
    holidayRateEnabled: false,
    holidayPercent: null,
  },
  {
    id: 6,
    workplaceId: 4,
    name: '家教',
    startTime: '19:00',
    endTime: '21:00',
    hourlyRate: null,
    dailyRate: null,
    breakMinutes: 0,
    breakPaid: false,
    nightRateEnabled: false,
    nightMultiplier: null,
    nightStart: null,
    nightEnd: null,
    holidayRateEnabled: false,
    holidayPercent: null,
  },
];

function shift(partial: Partial<Shift> & { id: number; date: string }): Shift {
  return {
    startTime: null,
    endTime: null,
    note: null,
    shiftTypeId: null,
    isHoliday: false,
    isRestDay: false,
    manualWageOverride: null,
    workplaceId: null,
    baseRate: null,
    breakMinutes: null,
    breakPaid: null,
    nightRateEnabled: null,
    nightMultiplier: null,
    nightStart: null,
    nightEnd: null,
    holidayRateEnabled: null,
    holidayPercent: null,
    ...partial,
  };
}

export const seedShifts: Shift[] = [
  // 正職辦公室(月薪,月結):出勤只影響工時,不影響金額;含一筆未來日期,驗證月薪固定算在「截至今日」
  shift({ id: 1, date: '2026-08-03', shiftTypeId: 1, startTime: '09:00', endTime: '18:00' }),
  shift({ id: 2, date: '2026-08-10', shiftTypeId: 1, startTime: '09:00', endTime: '18:00' }),
  shift({ id: 3, date: '2026-08-17', shiftTypeId: 1, startTime: '09:00', endTime: '18:00' }),
  shift({ id: 4, date: '2026-08-24', shiftTypeId: 1, startTime: '09:00', endTime: '18:00' }),
  shift({ id: 5, date: '2026-08-15', isRestDay: true }),

  // 超商時薪工讀(時薪,週結):早班/晚班(部分深夜)/夜班(全部深夜)/假日加給/手動覆寫,past+future 都有
  shift({ id: 6, date: '2026-08-03', shiftTypeId: 2, startTime: '09:00', endTime: '17:00' }),
  shift({ id: 7, date: '2026-08-04', shiftTypeId: 3, startTime: '17:00', endTime: '22:00' }),
  shift({ id: 8, date: '2026-08-05', shiftTypeId: 2, startTime: '09:00', endTime: '17:00', isHoliday: true }),
  shift({ id: 9, date: '2026-08-10', shiftTypeId: 4, startTime: '22:00', endTime: '06:00' }),
  shift({ id: 10, date: '2026-08-12', shiftTypeId: 2, startTime: '09:00', endTime: '17:00', manualWageOverride: 3000 }),
  shift({ id: 11, date: '2026-08-21', shiftTypeId: 2, startTime: '09:00', endTime: '17:00' }),
  shift({ id: 12, date: '2026-08-22', shiftTypeId: 3, startTime: '17:00', endTime: '22:00' }),
  shift({ id: 13, date: '2026-08-25', shiftTypeId: 2, startTime: '09:00', endTime: '17:00' }),

  // 工地日薪師傅(日薪,日結):固定金額,past+future,含一筆手動覆寫
  shift({ id: 14, date: '2026-08-02', shiftTypeId: 5, startTime: '07:00', endTime: '16:00' }),
  shift({ id: 15, date: '2026-08-09', shiftTypeId: 5, startTime: '07:00', endTime: '16:00' }),
  shift({ id: 16, date: '2026-08-16', shiftTypeId: 5, startTime: '07:00', endTime: '16:00' }),
  shift({ id: 17, date: '2026-08-23', shiftTypeId: 5, startTime: '07:00', endTime: '16:00' }),
  shift({ id: 18, date: '2026-08-30', shiftTypeId: 5, startTime: '07:00', endTime: '16:00', manualWageOverride: 1800 }),

  // 家教兼職(時薪,還沒設定發薪日):驗證發薪日曆的「還沒設定發薪日」提示
  shift({ id: 19, date: '2026-08-06', shiftTypeId: 6, startTime: '19:00', endTime: '21:00' }),
  shift({ id: 20, date: '2026-08-20', shiftTypeId: 6, startTime: '19:00', endTime: '21:00' }),
];

export const seedReportTemplates: ReportTemplate[] = [];
